spring:
  datasource:
    url: jdbc:mysql://192.168.233.131:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: luojiaxuan
    password: ljx991108
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 192.168.233.131
    port: 6379
    timeout: 3000
    password: ljx991108
